# palette = "catppuccin_frappe"
add_newline = false

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"
# other symbols "❯",">","->","==>"

[directory]
truncation_length = 4
# Catppuccin 'lavender'
style = "bold teal"

[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[hostname]
disabled = true